plantuml-editor:
  openai:
    api-key: ${OPENAI_API_KEY:false}
    allowed-frontend-api-keys: ${OPENAI_ALLOWED_FRONTEND_API_KEYS:}
    chat: ${OPENAI_CHAT:true}
    model: ${OPENAI_MODEL:gpt-3.5-turbo}
    max-tokens: ${OPENAI_MAX_TOKENS:1000}