server:
  port: 8081
plantuml-editor:
  document:
    lifetime: ${DOCUMENT_LIFETIME:PT168H}
    reaper:
      cron: ${DOCUMENT_REAPER_CRON:0 0/10 * * * ?}
  webdav:
    collection: ${WEBDAV_COLLECTION:}
    secret: ${WEBDAV_SECRET}
    url: ${WEBDAV_URL}
    username: ${WEBDAV_USERNAME}
    password: ${WEBDAV_PASSWORD}